easy_admin:
    entities:
        # List the entity class name you want to manage
        Produit:
            class: App\Entity\Produit
            form :
                fields:
                    - name
                    - description
                    - price
                    - isPublished
                    - imageName
                    - categories
                    - author
                    - tags
            list :
                fields: [name,isPublished, categories, author]
        Category:
            class: App\Entity\Category
        User:
            class: App\Entity\User
        Tag:
            class: App\Entity\Tag

    site_name: Administration mondocine

