#index:
#    path: /
#    controller: App\Controller\HomeController::index
#app_homepage:
#    path: /
#    controller: App\Controller\HomeController::index
app_logout:
  path: /logout
  methods: GET
ajax_route:
  path:     /ajax_request/{id}
  defaults:
    _controller: App\Controller\ProduitController:updateNbViews
  methods: [get]